import csv, sys, json

paints = []

def to_colour(rowslice):
    return {
        "munsell": [rowslice[0], float(rowslice[1]), float(rowslice[2])],
        "lab": [float(f) for f in rowslice[3:6]]
    }

with open(sys.argv[1], newline='') as csvfile:
    csvreader = csv.reader(csvfile)
    # Skip the header row
    next(csvreader)
    for row in csvreader:
        paints.append({
            "name": row[0],
            "thin": to_colour(row[1:7]),
            "thick": to_colour(row[7:13])
        })

jsonstr = ",\n".join(json.dumps(paint) for paint in paints)
filecontents = f"""
/** Autogenerated paint color value list
 * This file was autogenerated from {sys.argv[1]} using {__file__}
 * It provides thin-film and opaque-disc colour measurements for paints (currently only Golden Acrylic)
 **/
export interface PaintColour {{
    munsell: [string, number, number];
    lab: [number, number, number];
}}
export interface Paint {{
    name: string;
    thin: PaintColour;
    thick: PaintColour;
}}
export const GoldenAcrylics: Paint[] = [{jsonstr}];
"""
if len(sys.argv) < 2 or sys.argv[2] == "-":
    print(filecontents)
else:
    with open(sys.argv[2], "w") as outfile:
        outfile.write(filecontents)